[project]
name = "stundenlohn-kalk"
version = "0.1.0"
description = "Stundenlohn Kalkulator - Berechnung von Stundensätzen für Unternehmen"
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.22.0",
    "pandas>=1.5.0",
]
